version: '3'

services:
  app:
    build: .
    environment:
      # APPLICATION
      APPLICATION_ENV: dev
      WEATHER_API_BASE_URL: http://api.openweathermap.org
      WEATHER_API_KEY: fd14307661e274e29d50e20f6df1f674
    volumes:
    - .:/www
    working_dir: /www/
    ports:
      - "81:80"
    depends_on:
    - jsonserver
  jsonserver:
    image: clue/json-server
    volumes:
        - ./data/city.list.json:/data/db.json